config/routes.rb
#Последний Листинг 8.49: Обработка флажка “remember me”. app/controllers/#sessions_controller.rb Листинг 10.1:  
#Листинг 3.37:
Rails.application.routes.draw do
    #Листинг 5.22: Маршруты для статических страниц. config/routes.rb Листинг 7.3:
 
root             'static_pages#home' 
#Листинг 10.1: Добавление ресурса для активаций аккаунта. config/routes.rb :11.29
resources :account_activations, only: [:edit]
resources :password_resets,     only: [:new, :create, :edit, :update]
resources :microposts,          only: [:create, :destroy]
resources :relationships,       only: [:create, :destroy]
resources :articles
resources :folders
resources :reports
resources :students


resources :users do #12.15
    member do
      get :following, :followers
    end
  end

get 'articles' => 'articles#index'
get 'folders'  =>   'folders/index'
#get 'static_pages/home'
 # get 'static_pages/help'
  #get 'static_pages/about'
  #get 'static_pages/users'
  #get 'static_pages/referatHartl'
  get 'static_pages/usersallowed'
 get "/static_pages/users"
get 'password_resets/new'
  get 'password_resets/edit'

get 'microposts'    => 'microposts#index'
get 'students'    => 'students#index'

  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
get 'referat' => 'static_pages#referat'
get 'july07' => 'static_pages#july07'
get 'signup'  => 'users#new'  #Листинг 5.33:Маршрут для страницы регистрации. config/
#Листинг 8.1
 get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'




#Листинг 5.33: Маршрут для страницы регистрации. config/routes.rb 
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  
ActiveAdmin.routes(self)
  #  root 'users#show' был  у Мелаш

  # Example of regular route:
  get 'attach_files' => 'migration#attach_files'
  post 'attach_files' => 'migration#attach_files_action'

  post 'api/reviews_by_chapter' => 'categories#reviews_by_chapter'
  post 'api/sections_by_review' => 'categories#sections_by_review'
  post 'api/subsections_by_section' => 'categories#subsections_by_section'
 end

app/controllers/static_pages_controller.rb
# :11.38 :12.48
class StaticPagesController < ApplicationController
  def home
    if logged_in?  #:11.45 feed_items
    #June_25 @micropost  = current_user.microposts.build


     @feed_items = current_user.feed.paginate(page: params[:page])

@student  = current_user.students.build
end
  end
  
def show
	@user = User.find(params[:id])
	    #@articles = Article.includes(:article_files, :author).all
	    #@conferences = current_user.conferences
#@microposts = @user.microposts.paginate(page: params[:page])
	  end
  
  def help
  end

  def about
  end

  def users
@users = User.all
  end

 def referat

  end

 def july07
  end

  #def students
  #end



  #def allstudents
  #end
  def referatHartl
  end

  def usersallowed
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
 def  formatted_time(time)  #доступен во всех View
time.strftime("%I:M%p")
end
end

app/views/static_pages/_shim.html.erb
#Листинг 5.9: Партиал для HTML shim. app/views/layouts/_shim.html.erb

<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | libr2020</title>
  </head>
  <body>
    <h1>Sample App</h1>
    <p>
      This is the about page for the

 <a href="libr2020.asf.dp.ua/">libr2020.asf.dp.ua</a>
  sample application.

</p>
  </p>
  </body>
</html>

# libr Sept01
<%#= render partial: 'common/header', locals: {active: 'home'} %>
<%#= render partial: 'users/user_info' %>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | libr2020</title>
  </head>
  <body>
    <h1>Sample App</h1>
    <p>
      This is the Contact page for the

 <a href="libr2020.asf.dp.ua/">libr2020.asf.dp.ua</a>
  sample application.

</p>
  </p>
  </body>
</html>

app/views/static_pages/help.html.erb
Листинг 3.30: Представление для страницы Help с заголовком на основе встроенного Ruby. ЗЕЛЕНЫЙ app/views/static_pages/help.html.erb

<% provide(:title, "Help") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | March_08</title>
  </head>
  <body>
    <h1>Help</h1>
    <p>
      Get help on the Ruby on Rails Tutorial at the
      <a href="http://www.railstutorial.org/#help">Rails Tutorial help
      section</a>.
      To get help on this sample app, see the
      <a href="http://www.railstutorial.org/book"><em>Ruby on Rails
      Tutorial</em> book</a>.
    </p>
  </body>
</html>

app/views/static_pages/home.html.erb
<!-- home :3.33 Листинг 5.2: app/views/static_pages/home.html.erb  Листинг :5.34 :11.35  -->
<% if logged_in? %>

            <div class="row">
 <aside class="col-md-4">
                <section class="user_info">
                  <%= render 'shared/user_info' %>
                </section>
   <!--  # :12.17  shared/stats -->
          <section class="stats">
                  <%= render 'shared/stats' %>
                </section>

          <section class="micropost_form"> June_25
                  <%#= render 'shared/micropost_form' %>
                </section>

 <section class="stud">
                  <%= render 'shared/student_form' %>
                </section>



<section class="stud">
                  <%#= render 'shared/stud_form' %>
                </section>



 </aside> 
          <!--  # :11.47  11.47 at home :11.49 удаление micropost -->
          <div class="col-md-8">
                <h3>Micropost Feed</h3>
                <%= render 'shared/feed' %>
              </div>
            </div> 
<% else %>
 
  <div class="center jumbotron">
    <h1>Welcome to ~/mst ruby  2.2.4 rails 4.1.2 !</h1>

    <h2>
      This is the home page for the
      <a href="http://www.railstutorial.org/">Ministry for students</a>
      sample application.
    </h2>

    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  </div>
<%= link_to image_tag("241084701.gif", alt: "logo") %>
  
<% end %>

app/views/static_pages/july07.html.erb
<h1>StaticPages#July07</h1>
<p>Find me in app/views/static_pages/July07.html.erb.</p>
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Самоучитель HTML4 | htmlbook.ru</title>
		<link rel="search" type="application/opensearchdescription+xml" title="htmlbook.ru" href="/sites/search/search.xml">
		<link rel="alternate" type="application/rss+xml" title="Материалы с htmlbook.ru" href="//feeds.feedburner.com/htmlbook">		
		<link href="/themes/hb/css/style.css" rel="stylesheet" media="all">
		<link href="/themes/hb/css/print.css" rel="stylesheet" media="print">
				<script src="/themes/hb/min/?g=js"></script>
			</head>
	<body>
		<header>

	<div id="book-navigation" class="block">
		<h2 class="block_title">Содержание</h2>		<div class="block_content ">
			<ul class="menu"><li class="first leaf"><a href="/samhtml/vvedenie-v-html">Введение в HTML</a></li>
<li class="leaf"><a href="/samhtml/instrumentariy">Инструментарий</a></li>
<li class="collapsed"><a href="/samhtml/tegi">Теги</a></li>
<li class="leaf"><a href="/samhtml/struktura-html-koda">Структура HTML-кода</a></li>
<li class="collapsed"><a href="/samhtml/tipy-tegov">Типы тегов</a></li>
<li class="collapsed"><a href="/samhtml/znacheniya-atributov-tegov">Значения атрибутов тегов</a></li>
<li class="collapsed"><a href="/samhtml/tekst">Текст</a></li>
<li class="collapsed"><a href="/samhtml/ssylki">Ссылки</a></li>
<li class="leaf"><a href="/samhtml/yakorya">Якоря</a></li>
<li class="collapsed"><a href="/samhtml/izobrazheniya">Изображения</a></li>
<li class="collapsed"><a href="/samhtml/spiski">Списки</a></li>
<li class="collapsed"><a href="/samhtml/tablitsy">Таблицы</a></li>
<li class="collapsed"><a href="/samhtml/freymy">Фреймы</a></li>
<li class="last collapsed"><a href="/samhtml/validatsiya-dokumentov">Валидация документов</a></li>
</ul>		</div>
	</div>
					<div id="block-6" class="block">
				<div class="block_content ">
			 Скачать Adobe Flash Player на <a href="http://free-software.com.ua/players/adobe-flash-player/" target="_blank">http://free-software.com.ua/players/adobe-flash-player/</a> для Windows 7. <br /> Читайте <a href="http://zhzh.info/publ/9-1-0-9036" target="_blank">отзывы о vps.ua</a> в статье на zhzh.info. <br /> Заказ - <a href="https://web-site.help" target="_blank" rel="nofollow">https://web-site.help</a> 		</div>
	</div>
			</aside>
				<div id="block-16" class="block">
				<div class="block_content ">
			<div id="yandex_rtb_R-A-31105-1"></div>
<script>
    (function(w, d, n, s, t) {
        w[n] = w[n] || [];
        w[n].push(function() {
            Ya.Context.AdvManager.render({
                blockId: "R-A-31105-1",
                renderTo: "yandex_rtb_R-A-31105-1",
                async: true
            });
        });
        t = d.getElementsByTagName("script")[0];
        s = d.createElement("script");
        s.type = "text/javascript";
        s.src = "//an.yandex.ru/system/context.js";
        s.async = true;
        t.parentNode.insertBefore(s, t);
    })(this, this.document, "yandexContextAsyncCallbacks");
</script>		</div>
	</div>
			<div id="sidebar">
					<div id="views-practical-popular" class="block">
		<h2 class="block_title">Популярные задачи</h2>		<div class="block_content ">
			<div class="view view-practical view-id-practical view-display-id-popular view-dom-id-45e9b78d0dd19a8936ed104f234614f7">
        
  
  
      <div class="view-content">
      <div class="item-list">    <ul>          <li class="">  
  <div class="views-field views-field-title">        <span class="field-content"><a href="/practical/eskiz">Эскиз</a></span>  </div></li>
          <li class="">  
  <div class="views-field views-field-title">        <span class="field-content"><a href="/practical/obyazatelnye-polya-formy">Обязательные поля формы</a></span>  </div></li>
          <li class="">  
  <div class="views-field views-field-title">        <span class="field-content"><a href="/practical/nalozhenie-sloev">Наложение слоев</a></span>  </div></li>
          <li class="">  
  <div class="views-field views-field-title">        <span class="field-content"><a href="/practical/zagolovki">Заголовки</a></span>  </div></li>
          <li class="">  
  <div class="views-field views-field-title">        <span class="field-content"><a href="/practical/forma-registratsii">Форма регистрации</a></span>  </div></li>
          <li class="">  
  <div class="views-field views-field-title">        <span class="field-content"><a href="/practical/vlozhennye-spiski">Вложенные списки</a></span>  </div></li>
          <li class="">  
  <div class="views-field views-field-title">        <span class="field-content"><a href="/practical/chereduyushchiesya-kvadraty">Чередующиеся квадраты</a></span>  </div></li>
          <li class="">  
  <div class="views-field views-field-title">        <span class="field-content"><a href="/practical/flag-yaponii">Флаг Японии</a></span>  </div></li>
          <li class="">  
  <div class="views-field views-field-title">        <span class="field-content"><a href="/practical/android-v-teni">Андроид в тени</a></span>  </div></li>
          <li class="">  
  <div class="views-field views-field-title">        <span class="field-content"><a href="/practical/pole-dlya-igry-v-gomoku">Поле для игры в гомоку</a></span>  </div></li>
      </ul></div>    </div>
  
  
  
  
  
  
</div>		</div>
	</div>
					<div id="block-10" class="block">
				<div class="block_content ">
			<div id="yandex_rtb_R-A-31105-5"></div>
<script>
    (function(w, d, n, s, t) {
        w[n] = w[n] || [];
        w[n].push(function() {
            Ya.Context.AdvManager.render({
                blockId: "R-A-31105-5",
                renderTo: "yandex_rtb_R-A-31105-5",
                async: true
            });
        });
        t = d.getElementsByTagName("script")[0];
        s = d.createElement("script");
        s.type = "text/javascript";
        s.src = "//an.yandex.ru/system/context.js";
        s.async = true;
        t.parentNode.insertBefore(s, t);
    })(this, this.document, "yandexContextAsyncCallbacks");
</script>		</div>
	</div>
	<div id="block-31" class="block">
				<div class="block_content ">
			<iframe src="https://b.tml.io/htmlbook" width="240" height="400" frameBorder="0"></iframe>		</div>
	</div>
			</div>			
			<div id="content" class="three-col">
								
								<div class="tabs">
				
				</div>
								<h1 class="title">Самоучитель HTML4</h1>
				﻿
	<div id="like">
		<div class="num_comments"><a href="#disqus_thread"></a></div>
		<script>
			var disqus_shortname = 'htmlbook';
			(function () {
				var s = document.createElement('script'); s.async = true;
				s.type = 'text/javascript';
				s.src = '//' + disqus_shortname + '.disqus.com/count.js';
				(document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
			}());
		</script>
	</div>					<div id="system-main" class="block">
				<div class="block_content ">
			<div class="info"><p class="date"><time datetime="2010-09-23">23.09.2010</time></p><p class="author">Влад Мержевич</p></div>
<div class="field field-name-body field-type-text-with-summary field-label-hidden"><div class="field-items"><div class="field-item even"><p>HTML (HyperText Markup Language, язык разметки гипертекста) — это система верстки, которая определяет, как и какие элементы должны располагаться на веб-странице. Информация на сайте, способ ее представления и оформления зависят исключительно от разработчика и тех целей, которые он перед собой ставит. </p>
<p>Данный самоучитель предназначен в первую очередь для начинающих,  только постигающих азы создания сайтов. Множество примеров, иллюстраций,  вопросов для проверки и заданий для самостоятельной работы помогут быстрее  изучить HTML. </p>

</div></div></div>  <div class="book-navigation">
    <ul class="menu"><li class="first leaf"><a href="/samhtml/vvedenie-v-html">Введение в HTML</a></li>
<li class="leaf"><a href="/samhtml/instrumentariy">Инструментарий</a></li>
<li class="collapsed"><a href="/samhtml/tegi">Теги</a></li>
<li class="leaf"><a href="/samhtml/struktura-html-koda">Структура HTML-кода</a></li>
<li class="collapsed"><a href="/samhtml/tipy-tegov">Типы тегов</a></li>
<li class="collapsed"><a href="/samhtml/znacheniya-atributov-tegov">Значения атрибутов тегов</a></li>
<li class="collapsed"><a href="/samhtml/tekst">Текст</a></li>
<li class="collapsed"><a href="/samhtml/ssylki">Ссылки</a></li>
<li class="leaf"><a href="/samhtml/yakorya">Якоря</a></li>
<li class="collapsed"><a href="/samhtml/izobrazheniya">Изображения</a></li>
<li class="collapsed"><a href="/samhtml/spiski">Списки</a></li>
<li class="collapsed"><a href="/samhtml/tablitsy">Таблицы</a></li>
<li class="collapsed"><a href="/samhtml/freymy">Фреймы</a></li>
<li class="last collapsed"><a href="/samhtml/validatsiya-dokumentov">Валидация документов</a></li>
</ul>
        <div class="page-links">
                          <a href="/samhtml/vvedenie-v-html" class="page-next" title="На следующую страницу">Введение в HTML<i class="arrow icon-next"></i></a>
          </div>
    
  </div>
 		</div>
	</div>
		
			<div id="block-26" class="block">
				<div class="block_content ">
			<div id="yandex_rtb_R-A-31105-2"></div>
<script>
    (function(w, d, n, s, t) {
        w[n] = w[n] || [];
        w[n].push(function() {
            Ya.Context.AdvManager.render({
                blockId: "R-A-31105-2",
                renderTo: "yandex_rtb_R-A-31105-2",
                async: true
            });
        });
        t = d.getElementsByTagName("script")[0];
        s = d.createElement("script");
        s.type = "text/javascript";
        s.src = "//an.yandex.ru/system/context.js";
        s.async = true;
        t.parentNode.insertBefore(s, t);
    })(this, this.document, "yandexContextAsyncCallbacks");
</script>		</div>
	</div>
				<p class="note comment-note">Не выкладывайте свой код напрямую в комментариях, он отображается некорректно. 
		Воспользуйтесь сервисом <a href="//cssdeck.com/labs" rel="nofollow">cssdeck.com</a> или <a href="//jsfiddle.net" rel="nofollow">jsfiddle.net</a>,
		сохраните код и в комментариях дайте на него ссылку. Так и результат сразу увидят.</p>

		<div id="disqus_thread"></div>
		<script>
        var disqus_shortname = 'htmlbook';
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    
    			</div>
		</div>


		<footer>
		<section>
			<h4>О сайте</h4>
			<p><a href="/help">Помощь</a></p>
			<p><a href="/about/copy">Копирование материалов</a></p>
			<p><a href="/about/error">Борьба с ошибками</a></p>
			<p><a href="/about/tech">Технологии</a></p>
			<p><a href="/about/search">Поисковый плагин</a></p>
		</section>
		<section>
			<h4>Основные разделы</h4>
			<p><a href="/content">Статьи</a></p>
			<p><a href="/blog">Блог</a></p>
			<p><a href="/practical">Практикум</a></p>
			<p><a href="/books">Цифровые книги</a></p>
			<p><a href="//htmlforum.io" rel="nofollow">Форум</a></p>
		</section>
		<section>
			<h4>HTML</h4>
			<p><a href="/samhtml">Самоучитель HTML</a></p>
			<p><a href="/xhtml">XHTML</a></p>
			<p><a href="/html">Справочник по HTML</a></p>
			<p><a href="/html5">HTML5</a></p>
		</section>
		<section>
			<h4>CSS</h4>
			<p><a href="/samcss">Самоучитель CSS</a></p>
			<p><a href="/css">Справочник по CSS</a></p>
			<p><a href="/faq">Рецепты CSS</a></p>
			<p><a href="/css3">CSS3</a></p>
		</section>
		<section>
			<h4>Сайт</h4>
			<p><a href="/samlayout">Вёрстка</a></p>
			<p><a href="/layout">Макеты</a></p>
			<p><a href="/webserver">Веб-сервер</a></p>
		</section>
		<section class="hosting">
			<a href="http://dh.it-patrol.ru/drupal_hosting">htmlbook.ru использует Друпал хостинг it-patrol</a>
		</section>
		<p class="li"><script src="/themes/hb/js/li.js"></script></p>
		<p class="copyright">&copy; 2002–2019 Влад Мержевич, по всем вопросам пишите по адресу vlad@htmlbook.ru</p>
		<p><a href="http://feeds.feedburner.com/htmlbook" rel="nofollow">Подпишитесь на материалы сайта по RSS</a></p>
		</footer>
		<script src="/themes/hb/js/ads.js"></script>
	</body>
</html>

app/views/static_pages/referatHartl.html.erb
<% provide(:title, "Referat") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | libr2020</title>
  </head>
  <body>
    <h1>Sample App</h1>
    <p>
      This is the Referat page for the

 <a href="libr2020.asf.dp.ua/">libr2020.asf.dp.ua</a>
  sample application.

</p>
  </p>
  </body>
</html>

app/views/static_pages/users.html.erb
#Листинг 2.7: Представление index для пользователей. app/views/users/index.html.erb
<p>branch usernew-static-controllers-aug30-new-registration
% provide(:title, 'All users') %>
<h1>All users</h1>
<h1>Студенты на libr.1gb.ua August 30</h1>

<table>
  <thead>
    <tr>
      <th>login</th>
      <th>phone</th>

      <th>email</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>


	<tbody>
<% @users.each do |user| %>
     	 <tr>
		         <td><%= user.login %></td>
		         <td><%= user.phone %></td>

<td><%= user.email %></td>
		         <td><%= user.name %></td>
	      </tr> 
	</tbody>
<% end %>
 
 

</table>
 <br>

<%= link_to 'New User', new_user_path %>

app/views/static_pages/usersallowed.html.erb
<h1>StaticPages#usersallowed</h1>
<p>Find me in app/views/static_pages/usersallowed.html.erb</p>