config/routes.rb
#Последний Листинг 8.49: Обработка флажка “remember me”. app/controllers/#sessions_controller.rb Листинг 10.1:  
#Листинг 3.37:
Rails.application.routes.draw do
    #Листинг 5.22: Маршруты для статических страниц. config/routes.rb Листинг 7.3:
 
root             'static_pages#home' 
#Листинг 10.1: Добавление ресурса для активаций аккаунта. config/routes.rb :11.29
resources :account_activations, only: [:edit]
resources :password_resets,     only: [:new, :create, :edit, :update]
resources :microposts,          only: [:create, :destroy]
resources :relationships,       only: [:create, :destroy]
resources :articles
resources :folders
resources :reports
resources :students


resources :users do #12.15
    member do
      get :following, :followers
    end
  end

get 'articles' => 'articles#index'
get 'folders'  =>   'folders/index'
#get 'static_pages/home'
 # get 'static_pages/help'
  #get 'static_pages/about'
  #get 'static_pages/users'
  #get 'static_pages/referatHartl'
  get 'static_pages/usersallowed'
 get "/static_pages/users"
get 'password_resets/new'
  get 'password_resets/edit'

get 'microposts'    => 'microposts#index'
get 'students'    => 'students#index'

  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
get 'referat' => 'static_pages#referat'
get 'july07' => 'static_pages#july07'
get 'signup'  => 'users#new'  #Листинг 5.33:Маршрут для страницы регистрации. config/
#Листинг 8.1
 get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'




#Листинг 5.33: Маршрут для страницы регистрации. config/routes.rb 
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  
ActiveAdmin.routes(self)
  #  root 'users#show' был  у Мелаш

  # Example of regular route:
  get 'attach_files' => 'migration#attach_files'
  post 'attach_files' => 'migration#attach_files_action'

  post 'api/reviews_by_chapter' => 'categories#reviews_by_chapter'
  post 'api/sections_by_review' => 'categories#sections_by_review'
  post 'api/subsections_by_section' => 'categories#subsections_by_section'
 end

app/models/student.rb
#Листинг 6.24: Валидация уникальности адресов электронной почты. ЗЕЛЕНЫЙ app/models/user.rb  !!!
class Student < ActiveRecord::Base

belongs_to :user
validates :user_id, presence: true, 
                    uniqueness: true

end


   private
     def student_params
           params.require(:student).permit(:fio, :user_id)
     end

app/controllers/students_controller.rb
class StudentsController < InheritedResources::Base

  private

    def student_params
      params.require(:student).permit(:country, :fio, :lastname, :firstname, :email, :comment, :user_id)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/'_form.html.erb
March_21
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>
      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<div class="field">
    <%= f.label :studid %><br>
    <%= f.number_field :id %>
  </div>

<div class="field">
    <%= f.label :userid %><br>
    <%= f.number_field :id %>
  </div>

 <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id  %>
  </div>

  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>


  <div class="field">
    <%= f.label :fio %><br>
    <%= f.text_field :fio %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_field :comment %>
  </div>
  
  

<div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/_form.erb
#March_23 /students/_form
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>
      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="field">
    <%= f.label :userxid %><br>
    <%= f.number_field :user_id  %>
  </div>

<div class="field">
    <%= f.label :studentsid %><br>
    <%= f.number_field :id %>
  </div>

  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>

  <div class="field">
    <%= f.label :fio %><br>
    <%= f.text_field :fio %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_field :comment %>
  </div>
  
 <!-- #Листинг 11.37: Партиал формы для создания микросообщений. app/views/shared/# #_micropost_form.html.erb  11.57 :11.62  shared/_micropost_form.html.erb -->

   <div class="field">
    <%= f.text_area :user_id, placeholder: "Compose new student..." %>
  </div>
  
  <%= f.submit "Sign up as student", class: "btn btn-primary" %>

 <span class="picture">
        <%#= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span>
               <%# end %>
               <div class="actions">
                   <%#= f.submit %>
                 </div>
<% end %>

app/views/students/_form_with model.html.erb
#March_21 2021 http://rusrails.ru/rails-form-helpers


<%= form_with model: @user do |form| %>
  Students:
  <ul>
    <%= form.fields_for :students do |students_form| %>
      <li>
        <%= students_form.label :fio %>
        <%= students_form.text_field :fio %>

        <%= students_form.label :user_id %>
        <%= students_form.text_field :user_id %>
        ...
      </li>
    <% end %>
  </ul>
<% end %>

app/views/students/_student.html.erb
 #Листинг 11.21: Партиал для отображения единичного микросообщения. app/views/# #microposts/_micropost.html.erb  11.49 :11.59 
<li id="<%= micropost.id %>">
  <%#= link_to gravatar_for(micropost.user) %>
  Листинг 11.21<span class="user"><%= link_to student.user.name, student.user %></span>
  
<span class="user_id"><%= student.user_id %></span>
 <%#= image_tag micropost.picture.url if micropost.picture? %>
<span class="timestamp">
</span>
  <!-- :11.49 удаление micropost -->
Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    <% if current_user?(micropost.user) %>
      <%= link_to "delete", micropost, method: :delete,
                                       data: { confirm: "You sure?" } %>
    <% end %>
  </span>
</li>

app/views/students/edit.html.erb
<h1>Sign up as student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<h1>Listing students</h1>

<table>
  <thead>
    <tr>
      <th>Country</th>
      <th>Fio</th>
      <th>Lastname</th>
      <th>Firstname</th>
      <th>Email</th>
      <th>Comment</th>
      <th>User_id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.country %></td>
        <td><%= student.fio %></td>
        <td><%= student.lastname %></td>
        <td><%= student.firstname %></td>
        <td><%= student.email %></td>
        <td><%= student.comment %></td>
        <td><%= student.user_id %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Country:</strong>
  <%= @student.country %>
</p>

<p>
  <strong>Fio:</strong>
  <%= @student.fio %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @student.lastname %>
</p>

<p>
  <strong>Firstname:</strong>
  <%= @student.firstname %>
<m/p>

<p>
  <strong>Email:</strong>
  <%= @student.email %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @student.comment %>
</p>

<p>
  <strong>User:</strong>
  <%= @student.user_id %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>