config/routes.rb
#Последний Листинг 8.49: Обработка флажка “remember me”. app/controllers/#sessions_controller.rb Листинг 10.1:  
#Листинг 3.37:
Rails.application.routes.draw do
    #Листинг 5.22: Маршруты для статических страниц. config/routes.rb Листинг 7.3:
 
root             'static_pages#home' 
#Листинг 10.1: Добавление ресурса для активаций аккаунта. config/routes.rb :11.29
resources :account_activations, only: [:edit]
resources :password_resets,     only: [:new, :create, :edit, :update]
resources :microposts,          only: [:create, :destroy]
resources :relationships,       only: [:create, :destroy]
resources :articles
resources :folders
resources :reports
resources :students


resources :users do #12.15
    member do
      get :following, :followers
    end
  end

get 'articles' => 'articles#index'
get 'folders'  =>   'folders/index'
#get 'static_pages/home'
 # get 'static_pages/help'
  #get 'static_pages/about'
  #get 'static_pages/users'
  #get 'static_pages/referatHartl'
  get 'static_pages/usersallowed'
 get "/static_pages/users"
get 'password_resets/new'
  get 'password_resets/edit'

get 'microposts'    => 'microposts#index'
get 'students'    => 'students#index'

  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
get 'referat' => 'static_pages#referat'
get 'july07' => 'static_pages#july07'
get 'signup'  => 'users#new'  #Листинг 5.33:Маршрут для страницы регистрации. config/
#Листинг 8.1
 get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'




#Листинг 5.33: Маршрут для страницы регистрации. config/routes.rb 
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  
ActiveAdmin.routes(self)
  #  root 'users#show' был  у Мелаш

  # Example of regular route:
  get 'attach_files' => 'migration#attach_files'
  post 'attach_files' => 'migration#attach_files_action'

  post 'api/reviews_by_chapter' => 'categories#reviews_by_chapter'
  post 'api/sections_by_review' => 'categories#sections_by_review'
  post 'api/subsections_by_section' => 'categories#subsections_by_section'
 end

app/views/shared/''''''_stud_form.html.erb
<!--#Листинг 12.16: Партиал для отображения статистики. app/views/shared/_stats.html.erb
user.following.name = <%#= @user.following.name %>   :12.23 app/views/users/show.html.erb   #<% @user ||= current_user %>
user.id in shared/_stud.html.erb = <%= @user.id %>

 #Листинг 11.37: Партиал формы для создания микросообщений. app/views/shared/# #_stud_form.html.erb  11.57 :11.62 shared/_stud_form.html.erb-->

<%#= form_for(@stud) do |f| %>
<%#= form_for(@student) do |f| %>
<%#= form_for(@micropost) do |f| %>

  <%= render 'shared/error_messages', object: f.object %>
  
<div class="field">Compose new user_id for student
    <%= f.text_area :user_id, placeholder: "Compose new user_id for student" %>
</div>


<%#= @user.student.fio %>
  <%= f.submit "Post", class: "btn btn-primary" %>

 <span class="picture">
        <%#= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span>
end
<% end %>

app/views/shared/'''_student_error_messages.html.erb
<!--  #Листинг 7.19: Партиал для отображения сообщений об ошибках отправки формы. app/#views/shared/_error_messages.html.erb   -->

<% if @student.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@student.errors.count, "error") %>.
    </div>
    <ul>
    <% @student.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/''_header.html.erb
#Листинг 5.10: Партиал для заголовка сайта. app/views/layouts/_header.html.erb
#{:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee, :arb, :jbuilder]}



<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   '#' %></li>
        <li><%= link_to "Help",   '#' %></li>
        <li><%= link_to "Log in", '#' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/shared/''_student_error_messages.html.erb
<!--  #Листинг 7.19: Партиал для отображения сообщений об ошибках отправки формы. app/#views/shared/_error_messages.html.erb   -->

<% if @student.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@student.errors.count, "error") %>.
    </div>
    <ul>
    <% @student.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/'_stud.html.erb
<!--#Листинг 12.16: Партиал для отображения статистики. app/views/shared/_stats.html.erb
user.following.name = <%#= @user.following.name %>   :12.23 app/views/users/show.html.erb  user.id in shared/_stud.html.erb = <%#= @user.id %>
<%#= @user.student.fio %>
-->


<% @user ||= current_user %>


<!-- #Листинг 11.37: Партиал формы для создания микросообщений. app/views/shared/# #_student_form.html.erb  11.57 :11.62-->
shared/_student_form.html.erb

<%= form_for(@student) do |f| %>

  <%= render 'shared/error_messages', object: f.object %>
  
<div class="field">
    <%= f.text_area :user_id, placeholder: "Compose new user_id for student" %>
</div>

  <%= f.submit "Post", class: "btn btn-primary" %>

 <span class="picture">
        <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span>
<% end %>

app/views/shared/'_stud_form.html.erb
#March_21 12-04  2021 http://rusrails.ru/rails-form-helpers
 Students:

<%#= form_with model: @user do |form| %>
 
  <ul>
    <%#= form.fields_for :students do |students_form| %>

      <li>
        <%#= students_form.label :fio %>
        <%#= students_form.text_field :fio %>

        <%#= students_form.label :user_id %>
        <%#= students_form.text_field :user_id %>
        
      </li>
    <%# end %>
  </ul>
<% #end %>

app/views/shared/_error_messages.html.erb
<!--  #Листинг 7.19: Партиал для отображения сообщений об ошибках отправки формы. app/#views/shared/_error_messages.html.erb   -->

<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<!--#Листинг 11.46: Партиал для ленты сообщений. app/views/shared/_feed.html.erb 
app/views/shared/_feed.html.erb
11.49 удаление micropost -->

<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<!-- #Листинг 11.37: Партиал формы для создания микросообщений. app/views/shared/# #_micropost_form.html.erb  11.57 :11.62  shared/_micropost_form.html.erb -->

<%= form_for(@micropost, html: { multipart: true }) do |f| %>

  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>

 <span class="picture">
        <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span>
<% end %>

app/views/shared/_stats.html.erb
<!-- #Листинг 12.16: Партиал для отображения статистики. app/views/shared/_stats.html.erb
#user.following.name = <%#= @user.following.name %>   :12.23 app/views/users/#show.html.erb    user.name = <%#= @user.name %>   user.id=<%#= @user.id %>  -->

<% @user ||= current_user %>

<%#= @user.student.fio %>


<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
  <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_student_form.html.erb
<!-- #Листинг 11.37: Партиал формы для создания микросообщений. app/views/shared/# #_micropost_form.html.erb  11.57 :11.62  shared/_micropost_form.html.erb -->

<% @user ||= current_user %>
<%= form_for(@student) do |f| %>


  <%= render 'shared/error_messages', object: f.object %>
  

<div class="field">
    <%#= f.text_area :user_id, placeholder: "Compose new student.user_id.." %>
<%#= f.number_field :user_id %>
<%= f.number_field :user_id %>
  </div>
  


<%= f.submit "Post", class: "btn btn-primary" %>

 <span class="picture">
        <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span>
<% end %>

app/views/shared/_user_info.html.erb
<!-- #Листинг 11.36: Партиал для боковой панели с информацией о пользователе. app/views/#shared/_user_info.html.erb   -->

<%#= link_to gravatar_for(current_user), current_user %>

<h1>current_user.name=<%= current_user.name %></h1>
user.id = <%= @current_user.id %>
user.email=<%= @current_user.email %>
<%#= @current_user.student.fio %>

<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>