config/routes.rb
#Последний Листинг 8.49: Обработка флажка “remember me”. app/controllers/#sessions_controller.rb Листинг 10.1:  
#Листинг 3.37:
Rails.application.routes.draw do
    #Листинг 5.22: Маршруты для статических страниц. config/routes.rb Листинг 7.3:
 
root             'static_pages#home' 
#Листинг 10.1: Добавление ресурса для активаций аккаунта. config/routes.rb :11.29
resources :account_activations, only: [:edit]
resources :password_resets,     only: [:new, :create, :edit, :update]
resources :microposts,          only: [:create, :destroy]
resources :relationships,       only: [:create, :destroy]
resources :articles
resources :folders
resources :reports
resources :students


resources :users do #12.15
    member do
      get :following, :followers
    end
  end

get 'articles' => 'articles#index'
get 'folders'  =>   'folders/index'
#get 'static_pages/home'
 # get 'static_pages/help'
  #get 'static_pages/about'
  #get 'static_pages/users'
  #get 'static_pages/referatHartl'
  get 'static_pages/usersallowed'
 get "/static_pages/users"
get 'password_resets/new'
  get 'password_resets/edit'

get 'microposts'    => 'microposts#index'
get 'students'    => 'students#index'

  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
get 'referat' => 'static_pages#referat'
get 'july07' => 'static_pages#july07'
get 'signup'  => 'users#new'  #Листинг 5.33:Маршрут для страницы регистрации. config/
#Листинг 8.1
 get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'




#Листинг 5.33: Маршрут для страницы регистрации. config/routes.rb 
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  
ActiveAdmin.routes(self)
  #  root 'users#show' был  у Мелаш

  # Example of regular route:
  get 'attach_files' => 'migration#attach_files'
  post 'attach_files' => 'migration#attach_files_action'

  post 'api/reviews_by_chapter' => 'categories#reviews_by_chapter'
  post 'api/sections_by_review' => 'categories#sections_by_review'
  post 'api/subsections_by_section' => 'categories#subsections_by_section'
 end

app/views/common/_header.html.erb
#common/_header
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="<%= active == 'home' ? 'active' : '' %>"><%= link_to('Домашняя страница', root_path) %></li>
        <li class="<%= active == 'bookmarks' ? 'active' : '' %>"><%= link_to('Панель закладок', folders_path) %></li>
        <li class="<%= active == 'articles' ? 'active' : '' %>"><%= link_to('Поиск статей', articles_path) %></li>
        <li class="<%= active == 'report' ? 'active' : '' %>"><%= link_to('Формирование отчетности', reports_path) %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%#= link_to("{current_user.login} : Выйти?", destroy_user_session_path, :method => :delete) %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>